/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estoque.view;

import br.com.estoque.connection.Sessao;
import br.com.estoque.model.bean.Categoria;
import br.com.estoque.model.bean.ConfigSistema;
import br.com.estoque.model.bean.Fornecedor;
import br.com.estoque.model.bean.Produto;
import br.com.estoque.model.bean.Usuario;
import br.com.estoque.model.dao.CategoriaDAO;
import br.com.estoque.model.dao.FornecedorDAO;
import br.com.estoque.model.dao.ProdutoDAO;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Rafael
 */
public class ViewCadastraProduto extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastraProdutos
     * @param user
     */
    public ViewCadastraProduto() {
        initComponents();    
        DefaultTableModel modeloProd = (DefaultTableModel) JTProdutos.getModel();
        JTProdutos.setRowSorter(new TableRowSorter(modeloProd));
        populaComboBoxCategoria();
        populaComboBoxForn();
        
        //JTProdutos.getColumnModel().getColumn(0).setPreferredWidth(0);
        JTProdutos.getColumnModel().getColumn(0).setMaxWidth(0);
        JTProdutos.getColumnModel().getColumn(0).setMinWidth(0);
        JTProdutos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        JTProdutos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        JTProdutos.getColumnModel().getColumn(1).setPreferredWidth(180);
        JTProdutos.getColumnModel().getColumn(2).setPreferredWidth(100);
        JTProdutos.getColumnModel().getColumn(3).setPreferredWidth(50);
        JTProdutos.getColumnModel().getColumn(4).setPreferredWidth(50);
        JTProdutos.getColumnModel().getColumn(5).setPreferredWidth(50);
        JTProdutos.getColumnModel().getColumn(6).setPreferredWidth(50);
        JTProdutos.getColumnModel().getColumn(7).setPreferredWidth(50);
        JTProdutos.getColumnModel().getColumn(8).setPreferredWidth(50);
        JTProdutos.getColumnModel().getColumn(9).setPreferredWidth(100);
        
        readTableProdutos();
    }
    
    public void readTableProdutos(){
        DefaultTableModel modeloProd = (DefaultTableModel) JTProdutos.getModel();
        modeloProd.setNumRows(0);
        ProdutoDAO dao = new ProdutoDAO();
        
        for(Produto p : dao.read()){
            modeloProd.addRow(new Object[]{
                p.getIdProduto(),                
                p.getDescricao(),
                p.getCodigoDeBarras(),
                p.getValorCusto(),
                p.getValorVenda(),
                p.getEstMinimo(),
                p.getQuantidade(),
                p.getUnidadeDeMedida(),
                p.getEstado(),
                p.getImagem(),
                p.getIdCategoria(),
                p.getIdFornecedor()
            });
        }  
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodProd = new javax.swing.JLabel();
        lblDescProd = new javax.swing.JLabel();
        txtDescProd = new javax.swing.JTextField();
        lblCatProd = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcbFornecedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtEstMin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        txtCodProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValorCusto = new javax.swing.JFormattedTextField();
        txtValorVenda = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbUniMed = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        lblImgProd = new javax.swing.JLabel();
        btnArquivoImg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTProdutos = new javax.swing.JTable();
        btnSalvarProd = new javax.swing.JButton();
        btnCancelarProd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAlterarProd = new javax.swing.JButton();
        btnExcluirProd = new javax.swing.JButton();
        txtFile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setResizable(false);

        lblCodProd.setText("Código:");

        lblDescProd.setText("Descrição:");

        lblCatProd.setText("Categoria:");

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jcbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCategoriaActionPerformed(evt);
            }
        });

        jLabel4.setText("Fornecedor:");

        jcbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jcbFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFornecedorActionPerformed(evt);
            }
        });

        jLabel5.setText("Estoque Mínimo:");

        jLabel6.setText("Quantidade");

        jLabel1.setText("Valor de Custo:");

        jLabel2.setText("Valor de Venda:");

        jLabel3.setText("Unidade de Medida:");

        jcbUniMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "KG", "MT", "CJ", "UN", "CX", "JG", "PR", "PCT", "LT" }));

        jLabel7.setText("Estado:");

        jcbEstado.setSelected(true);
        jcbEstado.setText("Habilitado");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImgProd, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImgProd, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );

        btnArquivoImg.setText("Arquivo");
        btnArquivoImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArquivoImgActionPerformed(evt);
            }
        });

        JTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProduto", "Descrição", "Cód Barras", "Valor de Custo", "Valor de Venda", "Estoque Mín.", "Quantidade", "Un Medida", "Estado", "Imagem", "Categoria", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTProdutos);
        if (JTProdutos.getColumnModel().getColumnCount() > 0) {
            JTProdutos.getColumnModel().getColumn(0).setResizable(false);
            JTProdutos.getColumnModel().getColumn(1).setResizable(false);
            JTProdutos.getColumnModel().getColumn(2).setResizable(false);
            JTProdutos.getColumnModel().getColumn(3).setResizable(false);
            JTProdutos.getColumnModel().getColumn(4).setResizable(false);
            JTProdutos.getColumnModel().getColumn(5).setResizable(false);
            JTProdutos.getColumnModel().getColumn(6).setResizable(false);
            JTProdutos.getColumnModel().getColumn(7).setResizable(false);
            JTProdutos.getColumnModel().getColumn(8).setResizable(false);
            JTProdutos.getColumnModel().getColumn(9).setResizable(false);
            JTProdutos.getColumnModel().getColumn(10).setResizable(false);
            JTProdutos.getColumnModel().getColumn(11).setResizable(false);
        }

        btnSalvarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/íconeCad.fw.png"))); // NOI18N
        btnSalvarProd.setText("   Salvar");
        btnSalvarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdActionPerformed(evt);
            }
        });

        btnCancelarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/iconeCan.fw.png"))); // NOI18N
        btnCancelarProd.setText("     Limpar");
        btnCancelarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdActionPerformed(evt);
            }
        });

        jButton2.setText("Add Categoria");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/atu.png"))); // NOI18N
        btnAlterarProd.setText("Alterar");
        btnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdActionPerformed(evt);
            }
        });

        btnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/iconeCan.fw.png"))); // NOI18N
        btnExcluirProd.setText("Excluir");
        btnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCatProd)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodProd)
                                    .addComponent(lblDescProd)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(188, 188, 188))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jcbFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(29, 29, 29)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEstMin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jcbUniMed, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnArquivoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSalvarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnArquivoImg)
                            .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCodProd)
                                    .addComponent(lblCatProd))
                                .addGap(30, 30, 30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbUniMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEstado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ViewCadastraCategoria CadCat = new ViewCadastraCategoria();
        CadCat.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void limpaFormProdutos(){
        txtCodProd.setText("");
        txtDescProd.setText("");
        txtEstMin.setText("");
        txtFile.setText("");
        txtQtd.setText("");
        txtValorCusto.setText("");
        txtValorVenda.setText("");
        jcbEstado.setSelected(true);
        jcbCategoria.setSelectedIndex(0);
        jcbFornecedor.setSelectedIndex(0);
        jcbUniMed.setSelectedIndex(0);
        lblImgProd.setIcon(null);
    }
    
    public void populaComboBoxCategoria(){     
        CategoriaDAO dao = new CategoriaDAO();
        Map<String,String> list = new HashMap<>();
        list = dao.listCat();
        Iterator it = list.entrySet().iterator();
        while (it.hasNext()){
            Map.Entry pairs = (Map.Entry) it.next();
            jcbCategoria.addItem(pairs.getValue());
        }
    }
    
    public void populaComboBoxForn(){
        FornecedorDAO dao = new FornecedorDAO();
        Map<String,String> list = new HashMap<>();
        list = dao.listFor();
        Iterator it = list.entrySet().iterator();
        while (it.hasNext()){
            Map.Entry pairs = (Map.Entry)it.next();
            jcbFornecedor.addItem(pairs.getValue());
        }
    }
    
    private void btnSalvarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdActionPerformed
      if((txtCodProd.getText().length() <= 0) || (txtDescProd.getText().length() <= 0) || (txtEstMin.getText().length() <= 0) || (txtQtd.getText().length() <= 0) || (txtValorCusto.getText().length() <= 0) || (txtValorVenda.getText().length() <= 0) || (jcbCategoria.getSelectedItem() == "Selecione") || (jcbFornecedor.getSelectedItem() == "Selecione") || (jcbUniMed.getSelectedItem() == "")){
          JOptionPane.showMessageDialog(null, "Favor preencher todos os campos obrigatórios");
      }else{
          Produto p = new Produto();
          ProdutoDAO dao = new ProdutoDAO();
          CategoriaDAO daoCat = new CategoriaDAO();
          FornecedorDAO daoFor = new FornecedorDAO();
          
          p.setCodigoDeBarras(txtCodProd.getText());      
          p.setIdCategoria(daoCat.readForDesc((String) jcbCategoria.getSelectedItem()));
          p.setDescricao(txtDescProd.getText());
          
          // Pegando id do usuario com Singleton
          Usuario user = new Usuario();
          user = Sessao.getInstance().getUsuario();
                  
          p.setIdUsuario(user.getIdUsuario());
          p.setIdFornecedor(daoFor.readIdForDesc((String) jcbFornecedor.getSelectedItem()));
          p.setEstMinimo(Integer.parseInt(txtEstMin.getText()));
          p.setQuantidade(Integer.parseInt(txtQtd.getText()));
          
          String valorCusto = txtValorCusto.getText();
          String valorCustoBanco = valorCusto.replace(",", ".");
          BigDecimal valorCustoBig = new BigDecimal(valorCustoBanco);
          p.setValorCusto(valorCustoBig);
          
          String valorVenda = txtValorVenda.getText();
          String valorVendaBanco = valorVenda.replace(",", ".");
          BigDecimal valorVendaBig = new BigDecimal(valorVendaBanco);
          p.setValorVenda(valorVendaBig);
                    
          p.setUnidadeDeMedida((String) jcbUniMed.getSelectedItem());
          if(jcbEstado.isSelected()){
              p.setEstado(true);
          }else{
              p.setEstado(false);
          }
          
          if("".equals(txtFile.getText())){
              txtFile.setText("Controle2\\src\\img\\imgNaoDisp.jpg");
              p.setImagem("imgNaoDisp.jpg");
          }else{
            File file = new File(txtFile.getText());
            p.setImagem(file.getName());
            // Envia a imagem para pasta de imagens de produto.
            //String origemArquivo = txtFile.getText();
            //String destinoArquivo = "C:\\Users\\Rafael\\Documents\\NetBeansProjects\\Controle2\\src\\img";
                try {
                    String origemArquivo = txtFile.getText();
                    ConfigSistema cam = new ConfigSistema();
                    String destinoArquivo = cam.caminhoConfig("2");
                    dao.CopyImg(origemArquivo, destinoArquivo);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao copiar imagem - " + ex);
                }
          }
            // Data para enviar para o banco. Data de cadastro do produto.
            LocalDate dataCadProd = LocalDate.now();
            p.setDataCadastro(dataCadProd);
            
          dao.create(p);      
          limpaFormProdutos();
          readTableProdutos();
      }  
        
       
    }//GEN-LAST:event_btnSalvarProdActionPerformed

    private void btnArquivoImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArquivoImgActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Procurar arquivo");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagem", "jpg","jpeg","png");
        
        fileChooser.setFileFilter(filter);
        int retorno = fileChooser.showOpenDialog(this);
        
        if(retorno == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getPath());
            txtFile.setEditable(false);
            txtFile.setText(file.getPath());
            
            // O código abaixo redimenciona a imagem
            lblImgProd.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgProd.getWidth(),lblImgProd.getHeight(), Image.SCALE_DEFAULT)));
            
           // O código abaixo não redimenciona a imagem
           // lblImgProd.setIcon(new ImageIcon(file.getPath()));
        }

    }//GEN-LAST:event_btnArquivoImgActionPerformed

    private void jcbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFornecedorActionPerformed

    private void btnCancelarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdActionPerformed
        limpaFormProdutos();
        JTProdutos.getSelectionModel().clearSelection();
        btnSalvarProd.setEnabled(true);
    }//GEN-LAST:event_btnCancelarProdActionPerformed

    private void jcbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCategoriaActionPerformed
        
    }//GEN-LAST:event_jcbCategoriaActionPerformed

    private void btnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdActionPerformed
        if(JTProdutos.getSelectedRow() != -1){
            if(JOptionPane.showConfirmDialog(null, "Deseja excluir o registro?", "Confirmação de exclusão!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                ProdutoDAO dao = new ProdutoDAO();
                int idProd = (int) JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 0);
                dao.delete(idProd);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!");
        }
        limpaFormProdutos();
        readTableProdutos();
        btnSalvarProd.setEnabled(true);
    }//GEN-LAST:event_btnExcluirProdActionPerformed

    private void JTProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTProdutosMouseClicked
        btnSalvarProd.setEnabled(false);
        if(JTProdutos.getSelectedRow() != -1){
            txtCodProd.setText(JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 2).toString());
            txtDescProd.setText(JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 1).toString());
            txtEstMin.setText(JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 5).toString());
            txtQtd.setText(JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 6).toString());
            txtValorCusto.setText(JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 3).toString());
            txtValorVenda.setText(JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 4).toString());
            txtFile.setText(JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 9).toString());
            
            int catSel = Integer.parseInt(JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 10).toString());
            CategoriaDAO catDao = new CategoriaDAO();
            Map<String,String> list = new HashMap<>();
            list = catDao.listCat();
            Iterator it = list.entrySet().iterator();
            while (it.hasNext()){
                Map.Entry pairs = (Map.Entry) it.next();
                int catSelMap = Integer.parseInt(pairs.getKey().toString());
                    if(catSel == catSelMap){
                        jcbCategoria.setSelectedItem(pairs.getValue());
                    }
            }
   
            
            // O código abaixo é para mostrar a imagem quando usuário clica em uma das ROWs do JTABLE de Produtos
            String pathname = "C:\\Users\\Rafael\\Documents\\NetBeansProjects\\Controle2\\src\\img\\" + txtFile.getText();
            File file = new File(pathname);
            ImageIcon image = new ImageIcon(file.getPath());
            txtFile.setEditable(false);
            txtFile.setText(file.getPath());
            lblImgProd.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgProd.getWidth(),lblImgProd.getHeight(), Image.SCALE_DEFAULT)));
        }
    }//GEN-LAST:event_JTProdutosMouseClicked

    private void btnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdActionPerformed
        if(JTProdutos.getSelectedRow() != -1){
            if(JOptionPane.showConfirmDialog(null, "Gostaria de alterar o registro?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                Produto p = new Produto();
                ProdutoDAO dao = new ProdutoDAO();
                
                
                p.setIdProduto((int) JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 0));
                
                Sessao sessao = Sessao.getInstance();
                p.setIdUsuario(sessao.getIdUser());
                
                CategoriaDAO catDAO = new CategoriaDAO();
                p.setIdCategoria(catDAO.readForDesc((String) jcbCategoria.getSelectedItem()));
                
                FornecedorDAO forDAO = new FornecedorDAO();
                p.setIdFornecedor(forDAO.readIdForDesc((String) jcbFornecedor.getSelectedItem()));
                
                p.setDescricao(txtDescProd.getText());
                p.setCodigoDeBarras(txtCodProd.getText());
                
                BigDecimal ValorCusto = new BigDecimal(txtValorCusto.getText());
                p.setValorCusto(ValorCusto);
                
                BigDecimal ValorVenda = new BigDecimal(txtValorVenda.getText());
                p.setValorVenda(ValorVenda);
                
                int estMin = Integer.parseUnsignedInt(txtEstMin.getText());
                p.setEstMinimo(estMin);
                
                int qtdProd = Integer.parseInt(txtQtd.getText());
                p.setQuantidade(qtdProd);
                
                
                p.setUnidadeDeMedida((String) jcbUniMed.getSelectedItem());
                
                if(jcbEstado.isSelected()){
                     p.setEstado(true);
                }else{
                     p.setEstado(false);
                }
                
                Produto prod = dao.readForId((int) JTProdutos.getValueAt(JTProdutos.getSelectedRow(), 0));
                p.setDataCadastro(prod.getDataCadastro());
                
                String camImagemComp = txtFile.getText();
                String camImagem = camImagemComp.replace("C:\\Users\\Rafael\\Documents\\NetBeansProjects\\Controle2\\src\\img\\", "");     
                p.setImagem(camImagem);
                
                
                dao.update(p);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um registro para alterar!");
        }
        limpaFormProdutos();
        JTProdutos.getSelectionModel().clearSelection();
        btnSalvarProd.setEnabled(true);
        readTableProdutos();
    }//GEN-LAST:event_btnAlterarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewCadastraProduto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTProdutos;
    private javax.swing.JButton btnAlterarProd;
    private javax.swing.JButton btnArquivoImg;
    private javax.swing.JButton btnCancelarProd;
    private javax.swing.JButton btnExcluirProd;
    private javax.swing.JButton btnSalvarProd;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Object> jcbCategoria;
    private javax.swing.JCheckBox jcbEstado;
    private javax.swing.JComboBox<Object> jcbFornecedor;
    private javax.swing.JComboBox<String> jcbUniMed;
    private javax.swing.JLabel lblCatProd;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblDescProd;
    private javax.swing.JLabel lblImgProd;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtDescProd;
    private javax.swing.JTextField txtEstMin;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JFormattedTextField txtValorCusto;
    private javax.swing.JFormattedTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
