/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estoque.view;

import br.com.estoque.connection.ConnectionFactory;
import br.com.estoque.model.bean.Produto;
import br.com.estoque.model.bean.RelatoriosThread;
import br.com.estoque.model.bean.TarefasAgendadas;
import br.com.estoque.model.dao.ProdutoDAO;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rafael
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewProduto
     */
    public ViewMain() {
        initComponents();  
        
        JTProdutosInicial.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        JTProdutosInicial.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        JTProdutosInicial.getColumnModel().getColumn(0).setMaxWidth(0);
        JTProdutosInicial.getColumnModel().getColumn(0).setMinWidth(0);
        JTProdutosInicial.getColumnModel().getColumn(1).setPreferredWidth(200);
        JTProdutosInicial.getColumnModel().getColumn(2).setPreferredWidth(40);
        JTProdutosInicial.getColumnModel().getColumn(3).setPreferredWidth(40);
        JTProdutosInicial.getColumnModel().getColumn(4).setPreferredWidth(40);
        
        readtableProdutos();
        
        if(JOptionPane.showConfirmDialog(null, "Deseja enviar relatório diário?", "Relatório Diário", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            TarefasAgendadas task = new TarefasAgendadas();
            try {
                task.enviaRelatorioDiario();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao enviar relatório diário - " + ex);
            }
        }
    }
    
    ViewAddEstoqueProdutos JtAddProd = new ViewAddEstoqueProdutos();
    ViewRemoveEstoqueProdutos JtRemProd = new ViewRemoveEstoqueProdutos();
    ViewProdutoConsultado JtProdCons = new ViewProdutoConsultado();
    
    public void readtableProdutos(){
        DefaultTableModel modeloProdInicial = (DefaultTableModel) JTProdutosInicial.getModel();
        modeloProdInicial.setNumRows(0);
        ProdutoDAO dao = new ProdutoDAO();
        
        for(Produto p : dao.read()){
            modeloProdInicial.addRow(new Object[]{
                p.getIdProduto(),
                p.getDescricao(),
                p.getValorVenda(),
                p.getQuantidade(),
                p.getEstMinimo()
            });
            
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadEntPri = new javax.swing.JButton();
        btnCadSaiPri = new javax.swing.JButton();
        btnConProPri = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTProdutosInicial = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtPesquisaMain = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        jCadProdutos = new javax.swing.JMenuItem();
        jCadUsu = new javax.swing.JMenuItem();
        jCadCat = new javax.swing.JMenuItem();
        jCadFor = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        jRelPro = new javax.swing.JMenuItem();
        jRelUsu = new javax.swing.JMenuItem();
        jRelCat = new javax.swing.JMenuItem();
        jRelFor = new javax.swing.JMenuItem();
        jFerEti = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jFerBac = new javax.swing.JMenuItem();
        jMenuConfig = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/com/estoque/view/Bundle"); // NOI18N
        setTitle(bundle.getString("ViewMain.title")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        btnCadEntPri.setText(bundle.getString("ViewMain.btnCadEntPri.text")); // NOI18N
        btnCadEntPri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadEntPriActionPerformed(evt);
            }
        });

        btnCadSaiPri.setText(bundle.getString("ViewMain.btnCadSaiPri.text")); // NOI18N
        btnCadSaiPri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadSaiPriActionPerformed(evt);
            }
        });

        btnConProPri.setText(bundle.getString("ViewMain.btnConProPri.text")); // NOI18N
        btnConProPri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConProPriActionPerformed(evt);
            }
        });

        JTProdutosInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProduto", "Produto", "Preço", "Quantidade", "Est. mínimo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTProdutosInicial.setSelectionBackground(new java.awt.Color(255, 153, 0));
        JTProdutosInicial.setShowVerticalLines(false);
        JTProdutosInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTProdutosInicialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTProdutosInicial);
        if (JTProdutosInicial.getColumnModel().getColumnCount() > 0) {
            JTProdutosInicial.getColumnModel().getColumn(0).setResizable(false);
            JTProdutosInicial.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton1.setText(bundle.getString("ViewMain.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPesquisaMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaMainActionPerformed(evt);
            }
        });
        txtPesquisaMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisaMainKeyTyped(evt);
            }
        });

        jButton2.setText(bundle.getString("ViewMain.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadEntPri, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadSaiPri, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConProPri, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPesquisaMain, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadEntPri, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadSaiPri, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConProPri, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisaMain, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MenuCadastros.setText(bundle.getString("ViewMain.MenuCadastros.text")); // NOI18N

        jCadProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jCadProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/package.png"))); // NOI18N
        jCadProdutos.setText(bundle.getString("ViewMain.jCadProdutos.text")); // NOI18N
        jCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadProdutosActionPerformed(evt);
            }
        });
        MenuCadastros.add(jCadProdutos);

        jCadUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jCadUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/user.png"))); // NOI18N
        jCadUsu.setText(bundle.getString("ViewMain.jCadUsu.text")); // NOI18N
        jCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadUsuActionPerformed(evt);
            }
        });
        MenuCadastros.add(jCadUsu);

        jCadCat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jCadCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/tag_blue.png"))); // NOI18N
        jCadCat.setText(bundle.getString("ViewMain.jCadCat.text")); // NOI18N
        jCadCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadCatActionPerformed(evt);
            }
        });
        MenuCadastros.add(jCadCat);

        jCadFor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jCadFor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/lorry.png"))); // NOI18N
        jCadFor.setText(bundle.getString("ViewMain.jCadFor.text")); // NOI18N
        jCadFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadForActionPerformed(evt);
            }
        });
        MenuCadastros.add(jCadFor);

        MenuPrincipal.add(MenuCadastros);

        MenuRelatorios.setText(bundle.getString("ViewMain.MenuRelatorios.text")); // NOI18N

        jRelPro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jRelPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/package.png"))); // NOI18N
        jRelPro.setText(bundle.getString("ViewMain.jRelPro.text")); // NOI18N
        jRelPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelProActionPerformed(evt);
            }
        });
        MenuRelatorios.add(jRelPro);

        jRelUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        jRelUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/user.png"))); // NOI18N
        jRelUsu.setText(bundle.getString("ViewMain.jRelUsu.text")); // NOI18N
        jRelUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRelUsuMouseClicked(evt);
            }
        });
        jRelUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelUsuActionPerformed(evt);
            }
        });
        MenuRelatorios.add(jRelUsu);

        jRelCat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jRelCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/tag_blue.png"))); // NOI18N
        jRelCat.setText(bundle.getString("ViewMain.jRelCat.text")); // NOI18N
        jRelCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelCatActionPerformed(evt);
            }
        });
        MenuRelatorios.add(jRelCat);

        jRelFor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        jRelFor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/lorry.png"))); // NOI18N
        jRelFor.setText(bundle.getString("ViewMain.jRelFor.text")); // NOI18N
        jRelFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelForActionPerformed(evt);
            }
        });
        MenuRelatorios.add(jRelFor);

        MenuPrincipal.add(MenuRelatorios);

        jFerEti.setText(bundle.getString("ViewMain.jFerEti.text")); // NOI18N

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/printer.png"))); // NOI18N
        jMenuItem9.setText(bundle.getString("ViewMain.jMenuItem9.text")); // NOI18N
        jFerEti.add(jMenuItem9);

        jFerBac.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jFerBac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/database_save.png"))); // NOI18N
        jFerBac.setText(bundle.getString("ViewMain.jFerBac.text")); // NOI18N
        jFerBac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFerBacActionPerformed(evt);
            }
        });
        jFerEti.add(jFerBac);

        jMenuConfig.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/cog.png"))); // NOI18N
        jMenuConfig.setText(bundle.getString("ViewMain.jMenuConfig.text")); // NOI18N
        jMenuConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConfigActionPerformed(evt);
            }
        });
        jFerEti.add(jMenuConfig);

        MenuPrincipal.add(jFerEti);

        MenuSair.setText(bundle.getString("ViewMain.MenuSair.text")); // NOI18N
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        MenuPrincipal.add(MenuSair);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadUsuActionPerformed
        ViewCadastraUsuario CadUser = new ViewCadastraUsuario();
        CadUser.setVisible(true);
    }//GEN-LAST:event_jCadUsuActionPerformed

    private void btnCadEntPriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadEntPriActionPerformed
        if(JTProdutosInicial.getSelectedRow() != -1){
            int index = JTProdutosInicial.getSelectedRow();
            TableModel model = JTProdutosInicial.getModel();
            
            String idProd = model.getValueAt(index, 0).toString();
            String descProd = model.getValueAt(index, 1).toString();
            String qtdProd = model.getValueAt(index, 3).toString();
            
            JtAddProd.setVisible(true);
            JtAddProd.lblIdProd.setText(idProd);
            JtAddProd.lblIdProd.setVisible(false); // Escondendo o ID na JFrame ViewAddEstoqueProdutos
            JtAddProd.lblNomeProd.setText(descProd);
            JtAddProd.lblQtd.setText(qtdProd);

        }else{
            JOptionPane.showMessageDialog(null, "Por favor, selecione um produto!");
        }
    }//GEN-LAST:event_btnCadEntPriActionPerformed

    private void btnCadSaiPriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadSaiPriActionPerformed
        if(JTProdutosInicial.getSelectedRow() != -1){
            int index = JTProdutosInicial.getSelectedRow();
            TableModel model =JTProdutosInicial.getModel();
            
            String idProd = model.getValueAt(index, 0).toString();
            String desProd = model.getValueAt(index, 1).toString();
            String qtdProd = model.getValueAt(index,3).toString();
                   
            JtRemProd.setVisible(true);
            JtRemProd.lblIdProd.setText(idProd);
            JtRemProd.lblIdProd.setVisible(false);
            JtRemProd.lblDescProd.setText(desProd);
            JtRemProd.lblQtdatual.setText(qtdProd);
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, selecione um produto!");
        }
    }//GEN-LAST:event_btnCadSaiPriActionPerformed

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        
    }//GEN-LAST:event_MenuSairActionPerformed

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        
        int sair = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }else{
            
        }
    }//GEN-LAST:event_MenuSairMouseClicked

    private void jCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadProdutosActionPerformed
        ViewCadastraProduto CadProd = new ViewCadastraProduto();
        CadProd.setVisible(true);
    }//GEN-LAST:event_jCadProdutosActionPerformed

    private void jCadCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadCatActionPerformed
        ViewCadastraCategoria CadCat = new ViewCadastraCategoria();
        CadCat.setVisible(true);
    }//GEN-LAST:event_jCadCatActionPerformed

    private void jCadForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadForActionPerformed
        ViewCadastraFornecedor CadFor = new ViewCadastraFornecedor();
        CadFor.setVisible(true);
    }//GEN-LAST:event_jCadForActionPerformed

    private void jFerBacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFerBacActionPerformed
        
    }//GEN-LAST:event_jFerBacActionPerformed

    private void jMenuConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConfigActionPerformed
        ViewConfiguracoes conf = new ViewConfiguracoes();
        conf.setVisible(true);
    }//GEN-LAST:event_jMenuConfigActionPerformed

    private void jRelProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelProActionPerformed
        ViewRelProd relProd = new ViewRelProd();
        relProd.setVisible(true);
    }//GEN-LAST:event_jRelProActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConProPriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConProPriActionPerformed
        if(JTProdutosInicial.getSelectedRow() != -1){
            int idProd = (int) JTProdutosInicial.getValueAt(JTProdutosInicial.getSelectedRow(), 0); 
            System.out.println(idProd);
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();
            p = dao.readForId(idProd);
            
            JtProdCons.setVisible(true);
            JtProdCons.lblDescCons.setText(p.getDescricao());
            //JtProdCons.lblFornCons.setText(p.getIdFornecedor());
            //JtProdCons.lblCatCons.setText(p.getIdCategoria());
            JtProdCons.lblValorCustoCons.setText(String.valueOf(p.getValorCusto()));
            JtProdCons.lblValorVendaCons.setText(String.valueOf(p.getValorVenda()));
            JtProdCons.lblQtdCons.setText(String.valueOf(p.getQuantidade()));
            //JtProdCons.lblDataCadCons.setText(LocalDate.parse(p.getDataCadastro()));
            JtProdCons.lblUniMedCons.setText(p.getUnidadeDeMedida());
            JtProdCons.lblEstMinCons.setText(String.valueOf(p.getEstMinimo()));
            //JtProdCons.lblImgCons.set
            
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, selecione um produto!");
        }
    }//GEN-LAST:event_btnConProPriActionPerformed

    private void txtPesquisaMainKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaMainKeyTyped
        
    }//GEN-LAST:event_txtPesquisaMainKeyTyped

    private void txtPesquisaMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaMainActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JTProdutosInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTProdutosInicialMouseClicked

    }//GEN-LAST:event_JTProdutosInicialMouseClicked

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained

    }//GEN-LAST:event_jPanel1FocusGained

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        readtableProdutos();
    }//GEN-LAST:event_formWindowActivated

    private void jRelUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRelUsuMouseClicked
        
    }//GEN-LAST:event_jRelUsuMouseClicked

    private void jRelUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelUsuActionPerformed
        Connection conn = ConnectionFactory.getConnection();
        String src = "Relatorios\\Usuarios\\RelatorioUsuariosTodos.jasper";
        JasperPrint jasperPrint = null;
        
        try {
            jasperPrint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar o relatório. - Erro: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperPrint, false);
        view.setSize(1024, 800);
        view.setZoomRatio((float) 0.85);
        view.setTitle("Relatório Usuários");
        view.setVisible(true);  
    }//GEN-LAST:event_jRelUsuActionPerformed

    private void jRelCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelCatActionPerformed
        String src = "Relatorios\\Categorias\\RelatorioCategoriasTodas.jasper";
        String titulo = "Relatório Categorias";
        
        RelatoriosThread rel = new RelatoriosThread(src, titulo);
        rel.start();
    }//GEN-LAST:event_jRelCatActionPerformed

    private void jRelForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelForActionPerformed
       String src = "Relatorios\\Fornecedores\\RelatorioFornecedores.jasper";
       String titulo = "Relatório de Fornecedores";
       
       RelatoriosThread rel = new RelatoriosThread(src, titulo);
       rel.start();
    }//GEN-LAST:event_jRelForActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable JTProdutosInicial;
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JButton btnCadEntPri;
    private javax.swing.JButton btnCadSaiPri;
    private javax.swing.JButton btnConProPri;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem jCadCat;
    private javax.swing.JMenuItem jCadFor;
    private javax.swing.JMenuItem jCadProdutos;
    private javax.swing.JMenuItem jCadUsu;
    private javax.swing.JMenuItem jFerBac;
    private javax.swing.JMenu jFerEti;
    private javax.swing.JMenuItem jMenuConfig;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jRelCat;
    private javax.swing.JMenuItem jRelFor;
    private javax.swing.JMenuItem jRelPro;
    private javax.swing.JMenuItem jRelUsu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPesquisaMain;
    // End of variables declaration//GEN-END:variables
}
